### ISSUE TITLE
How to run with given proceename to hide

### ISSUE THREAD

**Issue by krishnareddyML** [Yaw-Dev/hideProcess-Py#1]
I am new to this, I am expecting that we can give required process name that need to be hide in task manager but in given python script i dint see where to give required process name to hide. please let me know

**Comment by Yaw-Dev** [comment]
You don't need to, the program that calls the `hideProcess()` function is the one that will be hidden.

**Comment by krishnareddyML** [comment]
Thanks for the response, so this script is not intended for hiding the process which are already running and showing in taskmanger. Ex: I have opened notepad, that is showing in taskmanager if i need to hide that one ? is it possible with this

**Comment by Yaw-Dev** [comment]
Short answer: It *might* be possible. 
I'm assuming that if you were to inject `hyde.dll` into the process you want to hide, it might work but I can't know for sure since I don't actually know how these DLL files work. As mentioned in README this repository is just a convertion of an AHK script to python. Maybe finding the original source of hyde.dll could help but I haven't really looked into it
